config/routes.rb
Rails.application.routes.draw do
  # admin
  devise_for :admins
  namespace :admin do
    resources :customers, only: %i[index show edit update]
    resources :cards, only: %i[index new create show edit update]
    get 'top' => 'cards#top'
  end

  # customer
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  root 'customer/cards#top'
  get 'about' => 'customer/cards#about'
  get 'contact' => 'customer/customers#contact'
  get 'terms_of_service' => 'customer/customers#terms_of_service'
  get 'privacy_policy' => 'customer/customers#privacy_policy'

  scope module: :customer do
    resources :cards, only: %i[top show index]
    get 'search' => 'cards#search'
    get 'customer/edit' => 'customers#edit'
    put 'customer' => 'customers#update'

    resource :customers, only: [:show] do
      collection do
        get 'quit'
        patch 'out'
        get :favorites
      end

      resources :cards do
        resource :favorites, only: %i[create destroy]
      end
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :kana_first_name, :kana_last_name,
            presence: true
  validates :kana_first_name, :kana_last_name,
            format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'カタカナで入力して下さい。' }

  has_many :cards, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # 退会機能
  def active_for_authentication?
    super && (is_valid == false)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:success] = '会員情報を変更しました。'
      redirect_to admin_customer_path
    else
      render 'edit'
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :kana_first_name, :kana_last_name, :email, :is_valid)
  end
end

app/controllers/customer/cards_controller.rb
class Customer::CardsController < ApplicationController
  def top
    @cards = Card.all
    @all_ranks = Card.find(Favorite.group(:card_id).order('count(card_id) desc').limit(3).pluck(:card_id))
  end

  def index
    @cards = Card.all
  end

  def show
    @cards = Card.all
    @card = Card.find(params[:id])
  end

  def search
    @cards = Card.search(params[:keyword])
    @keyword = params[:keyword]
    render 'index'
  end

  def about; end

  private

  def card_params
    parmas.require(:card).permit(:image, :name, :description)
  end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  def show
    @customer = current_customer
    @cards = @customer.cards

    favorites = Favorite.where(customer_id: current_customer.id).pluck(:card_id)
    @favorite_list = Card.find(favorites)
  end

  def quit; end

  def out
    @customer = current_customer
    @customer.update(is_valid: true)

    reset_session
    flash[:notice] = 'またのご利用を心よりお待ちしております。'
    redirect_to root_path
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    render :edit and return unless @customer.update(customer_params)

    flash[:success] = '登録情報を変更しました。'
    redirect_to customers_path
  end

  def contact; end

  def terms_of_service; end

  def privacy_policy; end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :email)
  end
end

app/controllers/customer/favorites_controller.rb
class Customer::FavoritesController < ApplicationController
  before_action :authenticate_customer!

  def create
    @card_favorite = Favorite.new(customer_id: current_customer.id, card_id: params[:card_id])
    @card_favorite.save
    redirect_to card_path(params[:card_id])
  end

  def destroy
    @card_favorite = Favorite.find_by(customer_id: current_customer.id, card_id: params[:card_id])
    @card_favorite.destroy
    redirect_to card_path(params[:card_id])
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  before_action :configure_sign_up_params, only: [:create]
  before_action :authenticate_customer!, only: %i[edit update]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?
      # respond_with resource, location: after_update_path_for(resource)
      flash[:success] = 'パスワード変更しました。'
      redirect_to customers_path
    else
      clean_up_passwords resource
      set_minimum_password_length
      redirect_to customers_path
      flash[:alert] = 'パスワードを変更できませんでした。'
    end
    # super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def customer_params
    params.require(:customers).permit(:password, :password_confirmation)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[name first_name last_name kana_first_name kana_last_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:password, :password_confirmation])
  # end

  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  def update_resource(resource, params)
    resource.update_with_password(params)
  end

  def after_update_path_for(resource)
    customers_path(resource)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  before_action :reject_customer, only: [:create]

  protected

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    unless @customer && (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false)); return; end

    flash[:alert] = 'このアカウントは退会済みです。'
    redirect_to new_customer_session_path
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/cards_helper.rb
module Customer::CardsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/favorites_helper.rb
module Customer::FavoritesHelper
end

app/views/customer/customers/_card_each.html.erb
<div class="card-container-mypage">
  <%= link_to card_path(card.id), class: "btn-link", :style=>"color:#FFF;" do %>
  <div id="img_field" class="card">
    <%= attachment_image_tag(card, :image, size: "200x150", fallback: "no_image.jpg") %>
  </div>
  <p class="cards-name">
    <%= card.name %>
  </p>
  <% end %>
</div>

app/views/customer/customers/contact.html.erb
<% provide(:title, "お問い合わせ") %>
<div class="row">
  <div class="col-xs-12">
    <h2 class="head-line title_h2 text-center">お問い合わせ</h2>
    <%= form_with url:root_path do |f| %>
      <div class="col-xs-offset-1 col-xs-10">
        <div class="form-group col-xs-12">
          <%= f.label :"氏名", class: "col-sm-3 control-label" %>
          <%= f.text_field :name, class: "col-sm-4 form-control-static name customer-form4" %>
        </div>
        <div class="form-group col-xs-12">
          <%= f.label :"メールアドレス", class: "col-sm-3 control-label" %>
            <%= f.email_field :mail, autofocus: true, autocomplete: "email", class: "col-sm-9 form-control-static customer-form4" %>
        </div>
        <div class="form-group col-xs-12">
          <%= f.label :"お問い合わせ内容", class: "col-sm-3 control-label" %>
          <%= f.text_area :comment,class: "col-sm-9 form-control-static customer-form4" %>
        </div>
        <div class="actions col-xs-7">
          <%= f.submit "送信", class: "btn btn-primary col-sm-3 pull-right" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/customer/customers/edit.html.erb
<% provide(:title, "登録情報編集") %>
<div class="row">
  <div class="col-xs-12">
    <h2 class="head-line title_h2 text-center">登録情報編集</h2>
    <%= form_with(model:@customer, url:customer_path, local: true ,method: :put) do |f| %>
      <%= render "layouts/error_messages", resource: @customer %>
        <div class="form-group col-xs-offset-1 col-xs-11">
          <%= f.label :"氏名", class: "col-sm-2 control-label customer-name-field" %>
          <%= f.label :"(姓)", class: "col-sm-1 control-label customer-name-field2 customer-name-field3" %>
          <%= f.text_field :last_name, class: "last_name col-sm-3 form-control-static name customer-form3" %>
          <%= f.label :"(名)", class: "col-sm-1 control-label customer-name-field2" %>
          <%= f.text_field :first_name, class: "first_name col-sm-3 form-control-static name customer-form3" %>
        </div>
        <div class="form-group col-xs-offset-1 col-xs-11">
          <%= f.label :"フリガナ", class: "col-sm-2 control-label customer-name-field" %>
          <%= f.label :"(セイ)", class: "col-sm-1 control-label customer-name-field2 customer-name-field3" %>
          <%= f.text_field :kana_last_name, class: "kana_last_name col-sm-3 form-control-static name customer-form3" %>
          <%= f.label :"(メイ)", class: "col-sm-1 control-label customer-name-field2" %>
          <%= f.text_field :kana_first_name, class: "kana_first_name col-sm-3 form-control-static name customer-form3" %>
        </div>
        <div class="col-xs-offset-1">
          <div class="form-group col-xs-10">
            <%= f.label :"メールアドレス", class: "col-sm-4 control-label" %>
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "col-sm-6 form-control-static customer-form3" %>
          </div>
        </div>

      <div class="actions col-xs-9 pull-right">
        <%= f.submit "編集内容を保存する", class: "btn btn-danger save col-xs-8 edit-btn"%>
        <%= link_to '退会する', quit_customers_path, class: "btn btn-warning col-xs-8 quit-btn"%>
      </div>
    <% end %>
    <div class="col-xs-12">
      <%= link_to "＜ 戻る", customers_path, class: "back-page" %>
    </div>
  </div>
</div>

app/views/customer/customers/privacy_policy.html.erb
<% provide(:title, "プライバシーポリシー") %>
<h2 class="text-center">プライバシーポリシー</h2><br>

ポイ活（以下，「当社」といいます。）は，本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。<br><br>

<h4>第1条（個人情報）</h4>
「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。<br><br>

<h4>第2条（個人情報の収集方法）</h4>
当社は，ユーザーが利用登録をする際に氏名，生年月日，住所，電話番号，メールアドレス，銀行口座番号，クレジットカード番号，運転免許証番号などの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を,当社の提携先（情報提供元，広告主，広告配信先などを含みます。以下，｢提携先｣といいます。）などから収集することがあります。<br><br>

<h4>第3条（個人情報を収集・利用する目的）</h4>
当社が個人情報を収集・利用する目的は，以下のとおりです。<br>

当社サービスの提供・運営のため<br>
ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）<br>
ユーザーが利用中のサービスの新機能，更新情報，キャンペーン等及び当社が提供する他のサービスの案内のメールを送付するため<br>
メンテナンス，重要なお知らせなど必要に応じたご連絡のため<br>
利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため<br>
ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため<br>
有料サービスにおいて，ユーザーに利用料金を請求するため<br>
上記の利用目的に付随する目的<br><br>

<h4>第4条（利用目的の変更）</h4>
当社は，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。
利用目的の変更を行った場合には，変更後の目的について，当社所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。<br><br>

<h4>第5条（個人情報の第三者提供）</h4>
当社は，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。<br>
人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき<br>
公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき<br>
国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき<br>
予め次の事項を告知あるいは公表し，かつ当社が個人情報保護委員会に届出をしたとき<br>
利用目的に第三者への提供を含むこと<br>
第三者に提供されるデータの項目<br>
第三者への提供の手段または方法<br>
本人の求めに応じて個人情報の第三者への提供を停止すること<br>
本人の求めを受け付ける方法<br>
前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。<br>
当社が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合<br>
合併その他の事由による事業の承継に伴って個人情報が提供される場合<br>
個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合<br><br>

<h4>第6条（個人情報の開示）</h4>
当社は，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。なお，個人情報の開示に際しては，1件あたり1，000円の手数料を申し受けます。<br>
本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合<br>
当社の業務の適正な実施に著しい支障を及ぼすおそれがある場合<br>
その他法令に違反することとなる場合<br>
前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。<br><br>

<h4>第7条（個人情報の訂正および削除）</h4>
ユーザーは，当社の保有する自己の個人情報が誤った情報である場合には，当社が定める手続きにより，当社に対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。<br>
当社は，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。<br>
当社は，前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。<br><br>

<h4>第8条（個人情報の利用停止等）</h4>
当社は，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。<br>
前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。
当社は，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。<br>
前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。<br><br>

<h4>第9条（プライバシーポリシーの変更）</h4>
本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。<br>
当社が別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。<br><br>

<div class="text-right">以上</div>

app/views/customer/customers/quit.html.erb
<% provide(:title, "退会ページ") %>
<div class="quit">
  <strong>本当に退会しますか？</strong>

    <div class="quit-msg">
      退会すると会員情報登録や<br>
      これまでのブックマークが閲覧できなくなります。<br>
      <br>
      退会する場合は,「退会する」をクリックしてください。
    </div>

    <%= link_to "退会しない", customers_path, class: 'btn btn-primary' %>
    <%= link_to "退会する", out_customers_path, method: :PATCH, data: {confirm: "本当に退会してもよろしいですか？"}, class: "btn btn-danger" %>

</div>

app/views/customer/customers/show.html.erb
<% provide(:title, "マイページ") %>
<div class="row">
	<div class="col-xs-11 pull-right">
		<h2 class="head-line text-left title_h2"><i class="far fa-user"></i>マイページ</h2>
		<p><strong class="information-link">登録情報</strong></p>
			<table class="mypage" frame="border">
				<div class="field">
					<tr>
						<th>氏名</th>
						<td class="text-left"><%= full_name(@customer) %></td>
					</tr>
					<tr>
						<th class="info">カナ</th>
						<td class="text-left"><%= kana_full_name(@customer) %></td>
					</tr>
					<tr>
						<th class="info">メールアドレス</th>
						<td class="text-left"><%= @customer.email %></td>
					</tr>
				</div>
			</table>	
			
			<div class="edit">
				<%= link_to " 編集", customer_edit_path, class: "glyphicon glyphicon-th-list btn btn-info" %>
				<%= link_to " パスワードを変更", edit_customer_registration_path, class: "glyphicon glyphicon-edit btn btn-warning" %>
			</div>

		<% if @favorite_list.present? %>
			<p><strong class="information-link">お気に入りカード</strong></p>
				<div class="card-container-mypage">
					<% @favorite_list.each do |card| %>
						<%= render "card_each", card: card %>
					<% end %>
				</div>
		<% end %>
	</div>
</div>