config/routes.rb
Rails.application.routes.draw do
  # admin
  devise_for :admins
  namespace :admin do
    resources :customers, only: %i[index show edit update]
    resources :cards, only: %i[index new create show edit update]
    get 'top' => 'cards#top'
  end

  # customer
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  root 'customer/cards#top'
  get 'about' => 'customer/cards#about'
  get 'contact' => 'customer/customers#contact'
  get 'terms_of_service' => 'customer/customers#terms_of_service'
  get 'privacy_policy' => 'customer/customers#privacy_policy'

  scope module: :customer do
    resources :cards, only: %i[top show index]
    get 'search' => 'cards#search'
    get 'customer/edit' => 'customers#edit'
    put 'customer' => 'customers#update'

    resource :customers, only: [:show] do
      collection do
        get 'quit'
        patch 'out'
        get :favorites
      end

      resources :cards do
        resource :favorites, only: %i[create destroy]
      end
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  attachment :image

  validates :name, :description, :annual_fee, :Reduction_rate, :point,
  presence: true

  def self.search(keyword)
    where('name LIKE ?', "%#{keyword}%")
  end

  belongs_to :customer, optional: true
  has_many :favorites, dependent: :destroy

  def favorited?(customer)
    favorites.where(customer_id: customer.id).exists?
  end
end

app/controllers/admin/cards_controller.rb
class Admin::CardsController < ApplicationController
  before_action :set_card, only: %i[show edit update]
  before_action :authenticate_admin!

  def top
    @cards = Card.all
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)
    if @card.save
      flash[:notice] = 'カードを登録しました。'
      redirect_to admin_card_path(@card)
    else
      render :new
    end
  end

  # GET /cards or /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1 or /cards/1.json
  def show
    @card = Card.find(params[:id])
  end

  # GET /cards/1/edit
  def edit
    @card = Card.find(params[:id])
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    @card = Card.find(params[:id])
    if @card.update(card_params)
      flash[:success] = 'カード内容を変更しました。'
      redirect_to admin_card_path(@card)
    else
      render :edit
    end
  end

  def search
    @cards = Card.search(params[:keyword])
    @keyword = params[:keyword]
    render 'index'
  end

  private

  # Only allow a list of trusted parameters through.
  def card_params
    params.require(:card).permit(:name, :description, :annual_fee, :Reduction_rate, :point, :image)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_card
    # @card = Card.find(params[:id])
  end
end

app/controllers/customer/cards_controller.rb
class Customer::CardsController < ApplicationController
  def top
    @cards = Card.all
    @all_ranks = Card.find(Favorite.group(:card_id).order('count(card_id) desc').limit(3).pluck(:card_id))
  end

  def index
    @cards = Card.all
  end

  def show
    @cards = Card.all
    @card = Card.find(params[:id])
  end

  def search
    @cards = Card.search(params[:keyword])
    @keyword = params[:keyword]
    render 'index'
  end

  def about; end

  private

  def card_params
    parmas.require(:card).permit(:image, :name, :description)
  end
end

app/helpers/admin/cards_helper.rb
module Admin::CardsHelper
end

app/helpers/customer/cards_helper.rb
module Customer::CardsHelper
end

app/views/admin/cards/_form_card.html.erb
  <div class="form-group">
    <%= f.label :カード名, style: "display: block" %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :説明, style: "display: block" %>
    <%= f.text_area :description, size: "45x10" %>
  </div>

  <div class="form-group">
    <%= f.label :年会費, style: "display: block" %>
    <%= f.text_field :annual_fee %>
  </div>

  <div class="form-group">
    <%= f.label :還元率, style: "display: block" %>
    <%= f.text_field :Reduction_rate %>
  </div>

  <div class="form-group">
    <%= f.label :ポイント名, style: "display: block" %>
    <%= f.text_field :point %>
  </div>

app/views/admin/cards/edit.html.erb
<% provide(:title, "カード編集") %>
<h2 class="head-line title_h2 text-center">カード編集</h2>
  <div class="row">

  <%= form_for(@card, url: admin_card_path, method: :patch, class: "form-horizontal") do |f| %>
    <%= render "layouts/error_messages", resource: @card%>
    <div class="col-md-offset-1 col-md-4 img-position">
      <div class="img_field">
        <%= attachment_image_tag(@card, :image, size: "250x180") %>
      </div>
      <div class="form-group ">
        <%= f.attachment_field :image, class: "image" %>
      </div>
    </div>

    <div class="col-md-6 card-explanation">
      <%= render "form_card", f: f %>
      <div class="actions col-xs-12 cards-show-edit">
	      <%= f.submit "保存", class: "btn btn-danger" %>
      </div>
    </div>
  <% end %>
  
  <div class="col-xs-12">
    <%= link_to "＜ 戻る", admin_card_path	, class: "back-page" %>
  </div>
</div>

app/views/admin/cards/index.html.erb
<% provide(:title, "カード一覧") %>
<h2 class="head-line text-center">カード一覧</h2>
<div class="row">
  <div class="col-xs-12">
    <table class="text-center admin-card-index" frame="border">
		  <div class="field">
        <tr>
          <th>ID</th>
          <th>カード名</th>
        </tr>

				<% @cards.each do |card| %>
  				<tr>
            <td class="col-xs-1">
              <%= card.id %>
            </td>
            <td class="text-left">
              <%= link_to admin_card_path(card), class: "btn-link" do %>
                <%= card.name %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </div>
    </table>
  </div>
  <div class="new-card">
    <%= link_to new_admin_card_path, data: {"turbolinks" => false}, class: "btn btn-warning pull-top" do %>
      カードを追加
    <% end %>
  </div>
</div>

app/views/admin/cards/new.html.erb
<% provide(:title, "カード新規登録") %>

<div class="row">
  <div class="col-xs-12">
    <h2 class="head-line title_h2 text-center">カード新規登録</h2>
    <%= form_for(@card, url: admin_cards_path, method: :post, class: "form-horizontal") do |f| %>
      <%= render "layouts/error_messages", resource: @card %>
      <div class="col-md-offset-1 col-md-4 img-position">
        <div class="img_field">
        </div>
  	      <%= f.attachment_field :image, class: "image" %>
      </div>
      <div class="col-md-6 card-explanation">
        <%= render "form_card", f: f %>
        <div class="actions col-xs-12 cards-show-edit">
          <%= f.submit "新規登録", class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>

    <div class="col-xs-12">
      <%= link_to "＜ 戻る", admin_cards_path	, class: "back-page" %>
    </div>
  </div>
</div>

app/views/admin/cards/show.html.erb
<% provide(:title, "カード詳細") %>
<h2 class="head-line title_h2 text-center">カード詳細</h2>
	<div class="row">
		<div class="col-md-offset-1 col-md-4 card-show">
			<div id="img_field">
				<%= attachment_image_tag(@card, :image, size: "250x180", fallback: "no_image.jpg") %>
	    </div>
    </div>
      <div class="col-md-6 card-explanation">
	      <div class="field">
					<p>
						カード名     <%= @card.name %>
					</p>
	      </div><br>
	      <div class="field">
					<p>
						カード説明     <%= @card.description %>
					</p><br>
	      </div>
	      <div class="field">
					<p>
						年会費      <%= @card.annual_fee %>
					</p><br>
	      </div>
	      <div class="field">
					<p>
						還元率    <%= @card.Reduction_rate %>
					</p><br>
	      </div>
	      <div class="field">
          <p>
            ポイント名    <%= @card.point %>
          </p><br>
        </div>
				<div class="actions col-xs-12 cards-show-edit">
				<%= link_to "編集", edit_admin_card_path(@card), data: {"turbolinks" => false}, class: "btn btn-warning " %>
				</div>
      </div>
    </div>
		<div class="col-xs-12 backbtn-cardshow">
      <%= link_to "＜ 戻る", admin_cards_path	, class: "back-page" %>
    </div>
	</div>

app/views/admin/cards/top.html.erb
<% provide(:title, "トップ") %>
<div class="row">
	<div class="col-xs-12">
		<h2 class="admin-head">管理者画面</h2>

		<div class="menu">
			<%= link_to "カード一覧", admin_cards_path, class: "menu_btn glyphicon glyphicon-credit-card"%>
		</div>

		<div class="menu">
			<%= link_to "会員一覧", admin_customers_path, class: "menu_btn glyphicon glyphicon-user"%>
		</div>
	</div>
</div>