config/routes.rb
Rails.application.routes.draw do
  # admin
  devise_for :admins
  namespace :admin do
    resources :customers, only: %i[index show edit update]
    resources :cards, only: %i[index new create show edit update]
    get 'top' => 'cards#top'
  end

  # customer
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }

  root 'customer/cards#top'
  get 'about' => 'customer/cards#about'
  get 'contact' => 'customer/customers#contact'
  get 'terms_of_service' => 'customer/customers#terms_of_service'
  get 'privacy_policy' => 'customer/customers#privacy_policy'

  scope module: :customer do
    resources :cards, only: %i[top show index]
    get 'search' => 'cards#search'
    get 'customer/edit' => 'customers#edit'
    put 'customer' => 'customers#update'

    resource :customers, only: [:show] do
      collection do
        get 'quit'
        patch 'out'
        get :favorites
      end

      resources :cards do
        resource :favorites, only: %i[create destroy]
      end
    end
  end
end

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if notice%>
	<div class="flash notice">
	  <span id="notice"><%= notice %></span>
	</div>
<% elsif flash[:success] %>
	<div class="flash success">
  	<span id="success"><%= flash[:success] %></span>
	</div>
<% elsif flash[:alert] %>
	<div class="flash danger">
	  <span id="alert"><%= flash[:alert] %></span>
	</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <ul class="footer-menu">
   <li>
     <%= link_to "about", about_path %> |
   </li>
   <li>
     <%= link_to "利用規約", terms_of_service_path %> |
   </li>
   <li>
     <%= link_to "プライバシーポリシー", privacy_policy_path %> |
   </li>
   <li>
     <%= link_to "お問い合わせ", contact_path %>
   </li>
   </ul>
  <p>Copyright © 2022. ポイ活</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar-left title">
    <% if admin_signed_in? %>
      <%= link_to "ポイ活", admin_top_path %>
    <% else %>
      <%= link_to "ポイ活", root_path %>
    <% end %>
  </nav>

    <li class="header-search">
      <%= render "layouts/search" %>
    </li>

    <div class="hamburger">
      <span></span>
      <span></span>
      <span></span>
    </div>

  <nav class="globalMenuSp">
    <ul class="nav navbar-nav navbar-right">
      <% if customer_signed_in? %>
        <li class="header-name">
          <%= link_to full_name(current_customer) + "さん", customers_path(current_customer), class: "header_btn glyphicon glyphicon-user"%>
        </li>
      <li>
        <%= link_to "ログアウト", destroy_customer_session_path, class: "header_btn glyphicon glyphicon-log-out" %>
      </li>
    
    <% elsif admin_signed_in? %>
      <li>
        <%= link_to "ログアウト", destroy_admin_session_path, class: "header_btn glyphicon glyphicon-log-out" %>
      </li>

    <% else %>
      <li>
        <%= link_to "新規登録", new_customer_registration_path, data: {"turbolinks" => false}, class: "header_btn glyphicon glyphicon-edit" %>
      </li>
      <li>
        <%= link_to "ログイン", new_customer_session_path, class: "header_btn glyphicon glyphicon-log-in" %>
      </li>
    <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_search.html.erb
<%= form_with url: search_path, method: :get, local: true do |f| %>
  <%= f.text_field :keyword, value: @keyword, placeholder: "キーワード検索", size:"50" %>
  <input type="submit" value="&#xf002">
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://fonts.googleapis.com/css2?family=Potta+One&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
    
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-YDDPX96PLP"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'G-YDDPX96PLP');
    </script> 

  </head>

  <body id="wrapper">
    <div id="header">
      <%= render "layouts/header" %>
    </div>
    <div class="container">
      <div id="flash">
        <%= render "layouts/flash" %>
      </div>
      <%= yield %>
    </div>
      <%= render "layouts/footer" %>
    </body>
</html>